spring:
  application.name: example
  cloud.function.definition: cats-birds|dogs-cats
management.endpoints.web.exposure.include: functions

cfgfns.replace:
  cats-birds:
    pattern: cats
    replace: birds
  dogs-cats:
    pattern: dogs
    replace: cats
