opensearch:
  chartVersion: 2.32.0

osdashboards:
  chartVersion: 2.28.0

kafka:
  chartVersion: 31.5.0

akhq:
  chartVersion: 0.25.1

fnflowprocessors:
    chartVersion: 0.0.1
    appversion: 0.0.1
    functionDefinition: idExist|idMatch
    cfgfns:
      hasValueValidator:
        idExist:
          elementPath: /id
      Match:
        idMatch:
          index: testindex
          template: testtemplate
          paramsFromInput:
            ids: /id
          literalParams:
            field: id

kafkaservice:
  chartVersion: 0.0.1
  appVersion: 0.0.4
  spring:
    kafka:
      producer:
        batch-size: 131072
        compression-type: lz4
        properties:
          linger.ms: 50
