apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnflow-json-processors-kafka
  labels:
    {{- include "fnflow-json-processors-kafka.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fnflow-json-processors-kafka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fnflow-json-processors-kafka.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: OPENSEARCH_URIS
              value: {{ .Values.opensearch.uris | quote }}
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: {{ .Values.kafka.brokers | quote }}
            - name: ORG_CT42_FNFLOW_FUNCTION_DEFINITION
              value: {{ .Values.function.definition | quote }}
          args: {{ list .Values.cfgfns "cfgfns" | include "recurseFlattenMap" | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
