management:
  server:
    port: 8079
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health.probes.enabled: true

spring:
  application.name: fnflow-json-processors-kafka
  cloud.function.definition: fnFlowComposedFnBean
