site:
  title: FnFlow
  start_page: fnflow::index.adoc
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: docs
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
    - asciidoctor-plantuml
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: docs/supplemental-ui
